protected:
  - VILLAGER
  - STRIDER
  - ARMOR_STAND
  - ITEM_FRAME
  - WOLF
  - BOAT
  - HORSE
  - ENDER_CRYSTAL
  - TRADER_LLAMA
  - WANDERING_TRADER
  - CAT
  - PAINTING
  - LEASH_HITCH
  - TROPICAL_FISH
  - MINECART
  - MINECART_CHEST
  - MINECART_HOPPER
  - MINECART_FURNACE
  - ELDER_GUARDIAN
  - GUARDIAN
  - DOLPHIN
  - LLAMA