main: entityManager.EntityManager
name: EntityManager
version: 1.5
description: Entity management plugin
api-version: 1.16
Author: _NickV

commands:
  entity:
    description: Entity manager command
    aliases: [em]